image: pmlrsg/gisportal-host

stages:
    - build

job1:
    stage: build
    script:
        - npm install --silent
        - export PYTHONPATH="$PYTHONPATH:/app/GISportal/plotting:/app/GISportal/plotting/data_extractor"
        - grunt
        - /usr/bin/redis-server --daemonize yes
        - npm test -- --reporter spec
