image: pmlrsg/gisportal-host

stages:
    - build

job1:
    stage: build
    script:
        - node --version
        - npm --version
        - npm install npm
        - ./node_modules/.bin/npm --version
        - ./node_modules/.bin/npm install --silent
        - grunt
        - /usr/bin/redis-server --daemonize yes
        - ./node_modules/.bin/npm test
